csdn:
  api:
    categories: Java场景面试宝典
    cookie: ${CSDN_API_COOKIE:uuid_tt_dd=10_20287133660-1749042697910-118142; UserName=A_ABai; UserToken=6e49377285444c92aa2a8c116f1f286a}


spring:
  application:
    name: okk-mcp-server-csdn

  ai:
    mcp:
      server:
        name: ${spring.application.name}
        version: 1.0.0

  main:
    banner-mode: off
# stdio 模式打开，sse 模式，注释掉。
    web-application-type: none

logging:
  # stdio 模式打开，sse 模式，注释掉。
  pattern:
    console:
  file:
    name: data/log/${spring.application.name}.log

server:
  port: 8101
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
